### ISSUE TITLE
feat: add support to register into venom.schema.json user defined executors

### ISSUE THREAD

**Issue by ivan-velasco** [Thiht/vscode-venom#6]
```yaml
testcases:
  - name: get_login_token
    steps:
    - type: get_login_token
```

Since this type is not present in the `venom.schema.json` we get an error in the editor

user defined executors is a common functionality used to avoid duplicate code. To have the plugin register the defined types in `lib` directory defined in the `.venomrc` would be really useful

Definition of the user defined executor:
```yaml
executor: get_login_token
input:
  arg: {}
steps:
  - script: sh ../../resources/scripts/gettoken.sh
    
output: 
   token: "{{.result.systemout}}"
```
